export const cars = [
  {
    name: "Honda",
    model: "uts",
    type: "suv",
    age: 2023,
    amount: 25,
    price: 29005,
    onSale: true,
  },
  {
    name: "Mazda",
    model: "Tucson",
    type: "sedan",
    age: 2022,
    price: 24000,
    amount: 5,
    onSale: false,
  },
  {
    name: "Daewoo",
    model: "lanos",
    type: "sedan",
    age: 2007,
    amount: 7,
    price: 30000,
    onSale: true,
  },
  {
    name: "BMV",
    model: "Accords",
    type: "suv",
    age: 2022,
    amount: 10,
    price: 20005,
    onSale: false,
  },
];
